--COALESCE(V1,V2,V3,V4.......) HASTA ENCONTRAR EL VALOR NO NULO
SELECT COALESCE(NULL,'VALOR1','VALOR2') FROM DUAL;
SELECT COALESCE('VALOR1',NULL,'VALOR2') FROM DUAL;
SELECT COALESCE(TO_CHAR(COMISSION_PCT),TO_CHAR(MANAGER_ID),'SIN JEFE NI COMISION') FROM EMPLOYEES; 