--NULLIF
SELECT NULLIF(1,1) FROM DUAL;
SELECT NULLIF(1,10) FROM DUAL;

SELECT COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2)), NULLIF(COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2))) FROM COUNTRIES;
SELECT COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2)), NULLIF(COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2))),
NVL2(NULLIF(COUNTRY_ID,UPPER(SUBSTR(COUNTRY_NAME,1,2))),'SON IGUALES','NO SON IGUALES') FROM COUNTRIES;