SELECT NVL(CITY,'NO TIENE'),NVL(STATE_PROVINCE,'NO TIENE') FROM LOCATIONS;
SELECT COALESCE(COMMISSION_PCT+SALARY,SALARY) AS "SALARIO TOTAL" FROM EMPLOYEES;
SELECT NVL(DEPARTMENT_ID,-1),NVL(MANAGER_ID,-1) FROM EMPLOYEES;
SELECT NULLIF(CITY,STATE_PROVINCE) FROM LOCATIONS;