--in
SELECT FIRST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE (DEPARTMENT_ID,SALARY) IN (
	SELECT DEPARTMENT_ID,MAX (SALARY) 
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID);

SELECT FIRST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(
	SELECT DEPARTMENT_ID 
	FROM DEPARTMENTS D 
	JOIN LOCATIONS L
	ON (D.LOCATION_ID=L.LOCATION_ID)
	AND CITY='Seatle');

--ANY
SELECT FIRST_NAME, LAST_NAME, JOB_ID,SALARY
FROM EMPLOYEES
WHERE SALARY > ANY(
	SELECT SALARY
	FROM EMPLOYEES
	WHERE JOB_ID='IT_PROG')
AND JOB_ID<>'IT_PROG';

--ALL
SELECT FIRST_NAME, LAST_NAME, JOB_ID,SALARY
FROM EMPLOYEES
WHERE SALARY > ALL(
	SELECT SALARY
	FROM EMPLOYEES
	WHERE JOB_ID='IT_PROG')
AND JOB_ID<>'IT_PROG';

