SELECT FIRST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY > ANY(
	SELECT MAX(SALARY) 
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
	HAVING DEPARTMENT_ID   
	IN (50,60,70));

SELECT DEPARTMENT_NAME 
FROM DEPARTMENTS
WHERE DEPARTMENT_ID IN(
	SELECT DEPARTMENT_ID
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID
	HAVING AVG(SALARY)>9000);

SELECT FIRST_NAME,DEPARTMENT_NAME,SALARY
FROM EMPLOYEES
JOIN DEPARTMENTS
USING (DEPARTMENT_ID)
WHERE (DEPARTMENT_ID,SALARY) IN 
	(SELECT DEPARTMENT_ID,MAX(SALARY)
	FROM EMPLOYEES
	GROUP BY DEPARTMENT_ID);

SELECT *
FROM EMPLOYEES	
WHERE SALARY > ALL(
	SELECT SALARY
	FROM EMPLOYEES
	WHERE DEPARTMENT_ID=100);

SELECT CITY 
FROM LOCATIONS LOC
WHERE EXISTS( 
	SELECT LOCATION_ID
	FROM DEPARTMENTS
	WHERE LOCATION_ID=LOC.LOCATION_ID);

SELECT REGION_NAME
FROM REGIONS
WHERE NOT EXISTS(
	SELECT REGION_ID 
	FROM COUNTRIES
	WHERE EXISTS (
		SELECT COUNTRY_ID 
		FROM LOCATIONS
		WHERE EXISTS(
			SELECT LOCATION_ID
			FROM DEPARTMENTS)));


