SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT MAX(SALARY) FROM EMPLOYEES;

SELECT MIN(SALARY) FROM EMPLOYEES;

SELECT MIN(SALARY),MAX(SALARY),AVG(SALARY) FROM EMPLOYEES;

SELECT AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=50;
