SELECT COUNT(FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(SALARY), COUNT(COMMISSION_PCT) FROM EMPLOYEES;

SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES;

SELECT COUNT(*) FROM EMPLOYEES WHERE SALARY>6000;

SELECT COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEES;

SELECT COUNT(DISTINCT DEPARTMENT_ID) FROM EMPLOYEES;

	