SELECT * FROM REGIONS 
NATURAL JOIN COUNTRIES;

SELECT DEPARTMENT_NAME,FIRST_NAME FROM EMPLOYEES 
JOIN DEPARTMENTS 
USING (DEPARTMENT_ID);

SELECT E.DEPARTMENT_ID, D.DEPARTMENT_NAME, E.FIRST_NAME,CITY FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON (D.LOCATION_ID=L.LOCATION_ID)
WHERE SALARY>5000;


