SELECT DEPARTMENT_NAME, FIRST_NAME
FROM DEPARTMENTS D JOIN EMPLOYEES E
ON D.DEPARTMENTS_ID=E.DEPARTMENTS_ID;

--LEFT OUTER JOIN
SELECT DEPARTMENT_NAME, FIRST_NAME
FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;
--RIGHT OUTER JOIN 
SELECT DEPARTMENT_NAME, FIRST_NAME
FROM DEPARTMENTS D RIGHT OUTER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;
--FULL OUTER JOIN
SELECT DEPARTMENT_NAME, FIRST_NAME
FROM DEPARTMENTS D FULL OUTER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;
--INNER JOIN



