SELECT COUNTRY_NAME,REGION_NAME,CITY FROM COUNTRIES NATURAL JOIN REGIONS NATURAL JOIN LOCATIONS;

SELECT D.DEPARTMENT_NAME,ROUND(AVG(E.SALARY),2) AS "MEDIA SALARIO"
FROM EMPLOYEES E
JOIN DEPARTMENTS USING (DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT JOB_TITLE, DEPARTMENT_NAME, LAST_NAME, HIRE_DATE 
FROM EMPLOYEES 
JOIN JOBS 
USING (JOB_ID)
JOIN DEPARTMENTS
USING (DEPARTMENT_ID)
WHERE TO_CHAR(HIRE_DATE,'YYYY')>'2000' AND TO_CHAR(HIRE_DATE,'YYYY')<'2004' ;

SELECT JOB_TITLE,AVG(SALARY)
FROM JOBS NATURAL JOIN EMPLOYEES
GROUP BY JOB_TITLE
HAVING AVG(SALARY) > 7000;

SELECT REGION_NAME,COUNT(*) AS "NUM DEPAR"
FROM REGIONS 
NATURAL JOIN COUNTRIES 
NATURAL JOIN LOCATIONS
NATURAL JOIN DEPARTMENTS
GROUP BY REGION_NAME;


SELECT FIRST_NAME,DEPARTMENT_NAME,COUNTRY_NAME 
FROM EMPLOYEES
JOIN DEPARTMENTS
USING (DEPARTMENT_ID)
JOIN LOCATIONS
USING (LOCATION_ID)
JOIN COUNTRIES
USING (COUNTRY_ID);


