SELECT TRABAJADOR.FIRST_NAME AS EMPLEADO, JEFE.FIRST_NAME AS JEFE
FROM EMPLOYEES TRABAJADOR JOIN EMPLOYEES JEFE
ON (TRABAJADOR.MANAGER_ID=JEFE.EMPLOYEE_ID)

SELECT DEPARTMENT_NAME,SUM(SALARY) 
FROM EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY  DEPARTMENT_NAME
ORDER BY SUM(SALARY) ASC;

SELECT CITY,DEPARTMENT_NAME 
FROM DEPARTMENTS 
RIGHT OUTER JOIN LOCATIONS 
USING LOCATION_ID
