--CASE SEARCHED
SELECT FIRST_NAME,SALARY,
CASE
	WHEN SALARY BETWEEN 0 AND 1000 THEN 'GANAS POCO'
	WHEN SALARY BETWEEN 1001 AND 5000 THEN 'GANAS LA MEDIA'
	WHEN SALARY > 5000 THEN 'PINCHE RICO'
	ELSE 'NO GANAS'
END
FROM EMPLOYEES;
	