SELECT FIRST_NAME, 
CASE 
	WHEN DEPARTMENT_ID = 50 THEN ' TRANSPORTE'
	WHEN DEPARTMENT_ID = 90 THEN ' DIRECCION'
	ELSE 'OTRO DEPARTAMENTO'
END
FROM EMPLOYEES;

SELECT CITY,
CASE
	WHEN COUNTRY_ID='US' OR COUNTRY_ID='CA' THEN ' AMERICA DEL NORTE'
	WHEN COUNTRY_ID='CH' OR COUNTRY_ID='UK' OR COUNTRY_ID='DE' OR COUNTRY_ID='IT' THEN ' EUROPA'
	WHEN COUNTRY_ID='BR' THEN 'AMERICA DEL SUR'
	ELSE 'OTRA ZONA'
END
FROM LOCATIONS;
