SELECT FIRST_NAME FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'MON')='MAY';
select *from employees where to_char(hire_date,'MM')=05;

SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'YYYY')=2007;

SELECT TO_CHAR(TO_DATE('23/02/1994'),'DAY') FROM DUAL;
SELECT * FROM EMPLOYEES WHERE TO_CHAR(HIRE_DATE,'MON')='JUN';

SELECT FIRST_NAME,TO_CHAR(SALARY,'$99999'),TO_CHAR(SALARY,'L99999') FROM EMPLOYEES;