--TO_CHAR(DATO,FORMATO)

/*
YYYY AÑO 4 NUMEROS
YEAR AÑO 2 DIGITOS
MM   MES 2 DIGITOS
DAY  DIA
DD   NUMERO DEL DIA
*/

SELECT SYSDATE,TO_CHAR(SYSDATE,'YYYY') FROM DUAL;
SELECT SYSDATE,TO_CHAR(SYSDATE,'MONTH') FROM DUAL;
SELECT SYSDATE,TO_CHAR(SYSDATE,'YEAR') FROM DUAL;

/* Horas
am pm
hh
h24
mi minuto
ss segundos
*/
SELECT SYSDATE, TO_CHAR(SYSDATE,'HH')FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE,'HH24')FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE,'MI')FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE,'HH24:MI')FROM DUAL;

SELECT TO_CHAR(SALARY,'999999') FROM EMPLOYEES;
SELECT TO_CHAR(SALARY,'L999999') FROM EMPLOYEES;
SELECT TO_CHAR(SALARY,'L999999.99') FROM EMPLOYEES;