/*DISTINC ELIMINA LOS DATOS DUPLICADOS*/

SELECT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FORM EMPLOYEES;


SELECT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID,JOB_ID FROM EMPLOYEES;

/*
Distinct
• Visualizar las ciudades donde hay departamentos, de la tabla locations. No deben salir repetidos
• Visualizar los distintos tipos de JOB_ID por departamento de la tabla Employees.
*/
SELECT DISTINCT CITY FROM locations;
SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;
