
SELECT DEPARTMENT_ID,SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_ID)
order by department_id;

SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID,JOB_ID
order by department_id;


SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS(DEPARTMENT_ID,JOB_ID)
order by department_id;

SELECT NULL,DEPARTMENT_ID,SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID
UNION ALL
SELECT JOB_ID,NULL,SUM(SALARY) FROM EMPLOYEES GROUP BY JOB_ID;

SELECT DEPARTMENT_ID,JOB_ID,MANAGER_ID,SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY GROUPING SETS((DEPARTMENT_ID,JOB_ID),(DEPARTMENT_ID,MANAGER_ID))
