/*
CARGA MASIVA DE DATOS
*/
CREATE TABLE NOM_EMPLES (
	COD_EMPLE NUMBER,
	FIRST_NAME VARCHAR(100)
);

CREATE TABLE SALARIOS (
	COD_EMPLE NUMBER,
	SALARIO VARCHAR(100)
);
INSERT ALL
	INTO NOM_EMPLES VALUES (EMPLOYEE_ID,FIRST_NAME)
	INTO SALARIOS VALUES (EMPLOYEE_ID,SALARY)
SELECT * FROM EMPLOYEES;

INSERT ALL
	INTO NOM_EMPLES VALUES (999,'PEDRO')
	INTO SALARIOS VALUES (999,1000)
SELECT 1 FROM DUAL





CREATE TABLE EMPLES_JEFES (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100),SALARIO NUMBER); 
CREATE TABLE EMPLES_MANDOS (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100),SALARIO NUMBER, DEPARTAMENTO NUMBER);
CREATE TABLE EMPLES_NORMALES (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100),SALARIO NUMBER, RESPONSABLE NUMBER);
CREATE TABLE FINANCIERO (COD_EMPLE NUMBER, NOMBRE VARCHAR2(100),SALARIO NUMBER, RESPONSABLE NUMBER);

INSERT ALL
	WHEN SALARY >10000 THEN
		INTO EMPLES_JEFES VALUES(EMPLOYEE_ID, FIRST_NAME||' '||LAST_NAME,SALARY)
	WHEN SALARY BETWEEN 8000 AND 10000 THEN 
		INTO EMPLES_MANDOS VALUES(EMPLOYEE_ID,FIRST_NAME||' '||LAST_NAME,SALARY,DEPARTMENT_ID)
	WHEN SALARY <8000 THEN 
		INTO EMPLES_NORMALES VALUES(EMPLOYEE_ID,FIRST_NAME||' '||LAST_NAME,SALARY,MANAGER_ID)
	WHEN DEPARTMENT_ID=100
		INTO FINANCIERO VALUES(EMPLOYEE_ID,FIRST_NAME||' '||LAST_NAME,SALARY,MANAGER_ID)
SELECT * FROM EMPLOYEES;


