SELECT *
FROM   (SELECT CLIENTE,PRODUCTO, CANTIDAD FROM   pivot)
PIVOT  (SUM(CANTIDAD) FOR (PRODUCTO) IN ('AGUACATES' AS "AGUACATES",'BANANAS' AS "BANANA",'MANZANA' AS "MANZANA",'NARANJA' AS "NARANJA"));

DROP TABLE UN_PIVOT;

CREATE TABLE UN_PIVOT AS
SELECT *
FROM   (SELECT CLIENTE,PRODUCTO, CANTIDAD FROM   pivot)
PIVOT  (SUM(CANTIDAD) FOR (PRODUCTO) IN ('AGUACATES' AS "AGUACATES",'BANANAS' AS "BANANA",'MANZANA' AS "MANZANA",'NARANJA' AS "NARANJA"));

SELECT * FROM UN_PIVOT;

SELECT * FROM UN_PIVOT 
UNPIVOT (CANTIDAD FOR PRODUCTO IN ("AGUACATES","BANANA","MANZANA","NARANJA"))
ORDER BY CLIENTE,PRODUCTO;