--LIMIAR VISUALIZACION
SELECT FIRST_NAME,SALARY FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;

--10 PERSONAS CON MAYOR SALARIO
SELECT FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 10 ROWS ONLY;

SELECT FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC FETCH FIRST 7 ROWS WHIT TIES;

--SALTATATE LAS PRIMERAS 5 FILAS
SELECT FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC OFFSET 5 ROWS FETCH FIRST 10 ROWS ONLY;

--PORCENTAJE
SELECT * FROM EMPLOYEES FETCH FIRST  20 PERCENT ROWS ONLY;

