SELECT SYSDATE+2 FROM DUAL;

SELECT HIRE_DATE, SYSDATE-HIRE_DATE FROM EMPLOYEES;

Select hire_date, trunc(sysdate - hire_date) as dias_pasados from employees ;

SELECT HIRE_DATE, TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) AS MESES_TRABAJANDO FROM EMPLOYEES; --CUANTOS MESES HAN PASADO 

SELECT SYSDATE,ADD_MONTHS(SYSDATE,3) FROM DUAL; --AGREGA MESES

SELECT SYSDATE,LAST_DAY('23/02/1994') FROM DUAL;--ULTIMA FECHA 
