SELECT CITY,COUNTRY_ID FROM LOCATIONS WHERE LENGTH(STREET_ADDRESS)>15 AND COUNTRY_ID='CA' OR COUNTRY_ID='US';
SELECT FIRST_NAME,(SALARY*14) AS 'SALARIO ANUAL' FROM EMPLOYEES WHERE INSTR(LAST_NAME,'b',3)<>0;
SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE SALARY>=4000 AND SALARY<=7000 AND INSTR(UPPER(FIRST_NAME),'A')<>0;
SELECT FIRST_NAME,LAST_NAME,SUBSTR(FIRST_NAME,1,1)||'.'||SUBSTR(LAST_NAME,1,1)||'.' as "Iniciales" FROM EMPLOYEES;
SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE INSTR(LAST_NAME,'B')<>0;
SELECT FIRST_NAME,LAST_NAME,SALARY,RPAD('*',SALARY/1000,'*') AS RANKING FROM EMPLOYEES;
