--REPLACE(CADENA, ORIGINAL, NUEVA)
SELECT REPLACE(FIRST_NAME,'a','@') FROM EMPLOYEES;

--LRTM RTRM
SELECT RTRIM('ALBERTO       ')||'PEREZ' FROM DUAL;
SELECT LTRIM('           ALBERTO')||'PEREZ' FROM DUAL;
