CREATE TABLE REGIONS1
(
	REGION_ID NUMBER,
	REGION_NAME VARCHAR(25)
);

INSERT INTO REGIONS1 VALUES (1,'Europe');
INSERT INTO REGIONS1 VALUES (2,'Asia');
INSERT INTO REGIONS1 VALUES (3,'Australia');
INSERT INTO REGIONS1 VALUES (4,'Antartica');
comit;

SELECT REGION_ID,REGION_NAME FROM REGIONS
UNION 
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

SELECT REGION_ID,REGION_NAME FROM REGIONS
UNION ALL 
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

SELECT REGION_ID,REGION_NAME FROM REGIONS
INTERSECT
SELECT REGION_ID,REGION_NAME FROM REGIONS1;

SELECT REGION_ID,REGION_NAME FROM REGIONS
MINUS
SELECT REGION_ID,REGION_NAME FROM REGIONS1;