CREATE TABLE EMPLEADOS 
AS SELECT * FROM EMPLOYEES;

CREATE TABLE EMPLEADOS_50
AS SELECT * FROM EMPLEADOS 
	WHERE DEPARTMENT_ID=50;

CREATE TABLE EMPLEADOS2
AS SELECT FIRST_NAME||' '||LAST_NAME AS NOMBRE, SALARY AS SALARIO,SALARY*12 AS NETO
FROM EMPLOYEES;