--INSERT
--INSERT INTO TABLE(C1,C2) VALUES (V1,V2);

INSERT INTO REGIONS(REGION_ID,REGION_NAME) VALUES (5,'Prueba1');

CREATE TABLE DEPT2 
(CODIGO NUMBER,
NOMBRE VARCHAR(100),
JEFE NUMBER
);

INSERT INTO DEPT2 VALUES (1,UPPER('informatica'),100);
INSERT INTO DEPT2 SELECT DEPARTMENT_ID,DEPARTMENT_NAME,MANAGER_ID 
FROM DEPARTMENTS
WHERE LOCATION_ID=1700;