INSERT INTO PRODUCTOS(CODIGO,NOMBRE,PRECIO,UNIDADES,FECHA_ALTA) 
	VALUES(1,'tornillos1',100,10,TO_DATE('01/09/2017'));

INSERT INTO PRODUCTOS VALUES(2,'tuercas',50,5,TO_DATE('01/10/2009'));

INSERT INTO PRODUCTOS VALUES(2,'martillo',90,NULL,NULL);

INSERT INTO PRODUCTOS (CODIGO,NOMBRE,unidades)
VALUES (4,'Arandela',10);

CREATE TABLE PRODUCTOS2
(
CODE NUMBER
NAME VARCHAR
);

INSERT INTO PRODUCTOS2 
SELECT CODIGO,NOMBRE
FROM PRODUCTOS
WHERE UNIDADES>8;


UPDATE PRODUCTOS 
SET NOMBRE =  UPPER(NOMBRE)
WHERE PRECIO>50;

UPDATE PRODUCTOS
SET PRECIO = 69
WHERE SUBSTR(NOMBRE,1,1) = 'T';

DELETE PRODUCTOS 
WHERE UNIDADES<10 OR UNIDADES IS NULL;

TRUNCATE TABLE PRODUCTOS2;
