CREATE TABLE EMPLEADOS(
	COD_MATRICULA NUMBER NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO1 VARCHAR(20) NOT NULL,
	APELLIDO2 VARCHAR(20) NOT NULL,
	EDAD NUMBER NOT NULL,
	FECHA_MATRICULA DATE
	);

CREATE TABLE CENTROS(
	CODIGO_CENTRO NUMBER,
	NOMBRE VARCHAR(100),
	PROVINCIA VARCHAR(100) DEFAULT 'MADRID',
	FECHA_ALTA DATE DEFAULT SYSDATE,
	NUM_ALUMNOS NUMBER DEFAULT 0
);

INSERT INTO CENTROS(CODIGO_CENTRO,NOMBRE) VALUES(1,'MATEMATICAS');
SELECT * FROM CENTROS;

CREATE TABLE CURSOS(
	COD_CURSOS NUMBER PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL UNIQUE,
	RESPONSABLE VARCHAR(100)
);
INSERT INTO CURSOS(COD_CURSOS,NOMBRE,RESPONSABLE) 
	VALUES(1,'VICENTE','COD');

INSERT INTO CURSOS(COD_CURSOS,NOMBRE,RESPONSABLE) 
	VALUES(1,'ANNA','CALL');


