CREATE TABLE PAISES(
	COD_PAIS NUMBER PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL 
		CHECK (NOMBRE=UPPER(NOMBRE))	
);

CREATE TABLE CIUDADES(
	COD_CIUDAD NUMBER PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL 
		CHECK (NOMBRE=UPPER(NOMBRE)),
	POBLACION NUMBER NOT NULL 
		CHECK (POBLACION > 0),
	COD_PAIS NUMBER,
	CONSTRAINT CIUDAD_PAIS FOREIGN KEY(COD_PAIS) REFERENCES PAISES(COD_PAIS)
);

INSERT INTO PAISES VALUES(1,'GRINGOLANDIA');
INSERT INTO PAISES VALUES(2,'ITALIA');

INSERT INTO CIUDADES VALUES(1,'NUEVA YORK',45,1);
INSERT INTO CIUDADES VALUES(1,'OHAIO',45,3);

INSERT INTO CIUDADES VALUES(1,'ROMA',0,2);