CREATE SEQUENCE SEQUENCE1 INCREMENT BY 1
MAXVALUE 1000 MINVALUE 20 CACHE 20;

SELECT SEQUENCE1.NEXTVAL FROM DUAL;
SELECT SEQUENCE1.CURRVAL FROM DUAL;

SELECT * FROM REGION1;

INSERT INTO REGION1 VALUES(SEQUENCE1.NEXTVAL,'AAAAA');
DROP SEQUENCE SEQUENCE1;
