--UPDATE TABLE SET COLUMNA=VALOR, COLUMNA=VALOR2 WHERE CONDICION

UPDATE DEPT2
SET JEFE = 100
WHERE CODIGO 120;

UPDATE DEPT2
SET JEFE = 200
WHERE JEFE IS NULL;

UPDATE DEPT2
SET JEFE = 
	(SELECT MANAGER_ID 
	FROM DEPARTMENTS 
	WHERE DEPARTMENT_ID=30)
WHERE CODIGO=100;
